[tools]
bazel = "latest"
buildifier = "latest"
"aqua:bazelbuild/buildtools/buildozer" = "latest"
hk = "latest"
node = "latest"
"npm:prettier" = "latest"
taplo = "latest"
typos = "latest"
yamlfmt = "latest"
