"mise hub repository"

load("@toml.bzl", "toml")

def _download_platform(rctx, name, url, checksum):
    ext = ".exe" if ".zip" in url else ""
    output = "tools/{}/executable{}".format(name, ext)

    is_archive = url.endswith(".tar.gz") or url.endswith(".tgz") or url.endswith(".zip")

    if is_archive:
        rctx.download_and_extract(
            url = url,
            sha256 = checksum,
            output = "tools/{}".format(name),
        )

        extract_dir = "tools/{}".format(name)
        result = rctx.execute(["find", extract_dir, "-name", "ruff*", "-type", "f"])
        found = [line for line in result.stdout.split("\n") if line]
        if found:
            src = found[0]
            rctx.execute(["cp", src, output])
            rctx.execute(["chmod", "+x", output])
    else:
        rctx.download(
            url = url,
            sha256 = checksum,
            output = output,
            executable = True,
        )

    return output

def _mise_hub_impl(rctx):
    parsed = toml.decode(rctx.attr.lockfile_content)
    tools_dict = parsed.get("tools", {})

    for tool_name, tool_data in tools_dict.items():
        if type(tool_data) == "list":
            tool_entries = tool_data
        else:
            tool_entries = [tool_data]

        for tool_entry in tool_entries:
            for platform_key, platform_data in tool_entry.items():
                if not platform_key.startswith("platforms."):
                    continue
                if "-musl" in platform_key:
                    continue
                if "arm64" in platform_key:
                    continue

                url = platform_data.get("url", "")
                checksum = platform_data.get("checksum", "")
                if checksum.startswith("sha256:"):
                    checksum = checksum[7:]

                if url and checksum:
                    _download_platform(rctx, tool_name, url, checksum)
                    break

        build_file_content = """# generated by mise

filegroup(
    name = "tool",
    srcs = ["executable"],
    visibility = ["//visibility:public"],
)
"""
        rctx.file("tools/{}/BUILD.bazel".format(tool_name), build_file_content)

    build_content = "# generated by mise\n\n"
    for tool_name in tools_dict.keys():
        build_content += """filegroup(
    name = "{}",
    srcs = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
)

""".format(tool_name)

    rctx.file("tools/BUILD.bazel", build_content)
    rctx.file("BUILD.bazel", "# generated by mise")

    return rctx.repo_metadata(reproducible = True)

_mise_hub = repository_rule(
    attrs = {
        "lockfile_content": attr.string(mandatory = True),
    },
    implementation = _mise_hub_impl,
)

def bzlmod_hub(name, lockfiles, module_ctx):
    all_content = ""
    for lockfile in lockfiles:
        all_content += module_ctx.read(lockfile)

    _mise_hub(name = name, lockfile_content = all_content)
