bazel_dep(name = "rules_mise", version = "0.0.0", dev_dependency = True)
bazel_dep(name = "bazel_skylib", version = "1.9.0", dev_dependency = True)

local_path_override(
    module_name = "rules_mise",
    path = "../..",
)

mise = use_extension("@rules_mise//mise:extensions.bzl", "mise")
mise.hub(lockfile = "//:mise.lock")
use_repo(mise, "mise")
