@rem Generated by rules_mise (run_in): execs the resolved tool with cwd %{{env_var}}%.
@set "tool=%~dp0{{tool_filename}}"
@if not exist "%tool%" set "tool=%cd%\{{tool}}"
@cd /D %{{env_var}}%
@"%tool%" %*
