#!/usr/bin/env bash
# Generated by rules_mise (run_in): execs the resolved tool with cwd "${{env_var}}".

# The tool output sits next to this wrapper in bazel-bin and in the runfiles
# tree, so prefer the sibling location and only fall back to runfiles lookups
# and the legacy workspace-relative path.
_wrapper="$0"
case "$_wrapper" in
  /*) ;;
  *) _wrapper="$PWD/$_wrapper" ;;
esac
_wrapper_dir="$(dirname "$_wrapper")"

tool=""
if [ -x "$_wrapper_dir/{{tool_filename}}" ]; then
  tool="$_wrapper_dir/{{tool_filename}}"
elif [ -n "${RUNFILES_DIR:-}" ] && [ -x "$RUNFILES_DIR/{{runfiles_path}}" ]; then
  tool="$RUNFILES_DIR/{{runfiles_path}}"
elif [ -n "${RUNFILES_MANIFEST_FILE:-}" ] && [ -f "$RUNFILES_MANIFEST_FILE" ]; then
  _manifest_tool="$(grep -m1 -F "{{runfiles_path}} " "$RUNFILES_MANIFEST_FILE" | cut -d ' ' -f 2-)"
  if [ -n "$_manifest_tool" ] && [ -x "$_manifest_tool" ]; then
    tool="$_manifest_tool"
  fi
  unset _manifest_tool
fi
if [ -z "$tool" ] && [ -x "$PWD/{{tool}}" ]; then
  tool="$PWD/{{tool}}"
fi
if [ -z "$tool" ]; then
  echo "rules_mise: cannot locate the wrapped tool (tried sibling '{{tool_filename}}', runfiles '{{runfiles_path}}', and '\$PWD/{{tool}}')" >&2
  exit 1
fi
unset _wrapper _wrapper_dir

cd "${{env_var}}" && exec "$tool" "$@"
